import type { Patient, Staff } from '../types';
import { DEFAULT_PASSWORD_HASH } from './auth';

// All sample staff ship with default password "password" and are flagged
// mustChangePassword=true. They are prompted to change it on first login.
export const sampleStaff: Staff[] = [
  {
    id: 'staff-1',
    employeeId: 'EMP001',
    firstName: 'Dr. Sarah',
    lastName: 'Johnson',
    role: 'physician',
    specialty: 'Emergency Medicine',
    department: 'Emergency',
    licenseNumber: 'MD-12345',
    phone: '555-0101',
    email: 'sjohnson@moromoke.hospital',
    status: 'active',
    shift: 'day',
    hireDate: '2018-03-15',
    npi: '1234567890',
    username: 'sjohnson',
    passwordHash: DEFAULT_PASSWORD_HASH,
    mustChangePassword: true,
  },
  {
    id: 'staff-2',
    employeeId: 'EMP002',
    firstName: 'Dr. Michael',
    lastName: 'Okonkwo',
    role: 'physician',
    specialty: 'Internal Medicine',
    department: 'Emergency',
    licenseNumber: 'MD-67890',
    phone: '555-0102',
    email: 'mokonkwo@moromoke.hospital',
    status: 'active',
    shift: 'evening',
    hireDate: '2020-07-01',
    npi: '0987654321',
    username: 'mokonkwo',
    passwordHash: DEFAULT_PASSWORD_HASH,
    mustChangePassword: true,
  },
  {
    id: 'staff-3',
    employeeId: 'EMP003',
    firstName: 'Nurse',
    lastName: 'Adeyemi',
    role: 'nurse',
    department: 'Emergency',
    phone: '555-0103',
    email: 'adeyemi@moromoke.hospital',
    status: 'active',
    shift: 'day',
    hireDate: '2019-11-20',
    username: 'adeyemi',
    passwordHash: DEFAULT_PASSWORD_HASH,
    mustChangePassword: true,
  },
  {
    id: 'staff-4',
    employeeId: 'EMP004',
    firstName: 'Nurse',
    lastName: 'Fatima',
    role: 'nurse',
    department: 'Emergency',
    phone: '555-0104',
    email: 'fatima@moromoke.hospital',
    status: 'active',
    shift: 'night',
    hireDate: '2021-01-10',
    username: 'fatima',
    passwordHash: DEFAULT_PASSWORD_HASH,
    mustChangePassword: true,
  },
  {
    id: 'staff-5',
    employeeId: 'EMP005',
    firstName: 'Dr. Blessing',
    lastName: 'Nwosu',
    role: 'np',
    specialty: 'Family Medicine',
    department: 'Emergency',
    phone: '555-0105',
    email: 'bnwosu@moromoke.hospital',
    status: 'active',
    shift: 'rotating',
    hireDate: '2022-04-05',
    username: 'bnwosu',
    passwordHash: DEFAULT_PASSWORD_HASH,
    mustChangePassword: true,
  },
  {
    id: 'staff-admin',
    employeeId: 'ADM001',
    firstName: 'System',
    lastName: 'Administrator',
    role: 'admin',
    department: 'Administration',
    phone: '555-0000',
    email: 'admin@moromoke.hospital',
    status: 'active',
    shift: 'day',
    hireDate: '2018-01-01',
    username: 'admin',
    passwordHash: DEFAULT_PASSWORD_HASH,
    mustChangePassword: true,
  },
];

export const samplePatients: Patient[] = [
  {
    id: 'pat-001',
    mrn: 'MRN20240001',
    firstName: 'James',
    lastName: 'Adeleke',
    dateOfBirth: '1978-03-22',
    gender: 'male',
    phone: '555-1001',
    email: 'jadeleke@email.com',
    address: {
      street: '14 Adeola Odeku St',
      city: 'Lagos',
      state: 'Lagos',
      zip: '101233',
      country: 'Nigeria',
    },
    bloodType: 'O+',
    maritalStatus: 'Married',
    emergencyContacts: [
      {
        id: 'ec-001',
        name: 'Mary Adeleke',
        relationship: 'Spouse',
        phone: '555-1002',
        email: 'madeleke@email.com',
      },
    ],
    insurance: {
      provider: 'NHIS',
      policyNumber: 'NHIS-001234',
      groupNumber: 'GRP-5678',
      subscriberName: 'James Adeleke',
      subscriberDOB: '1978-03-22',
      relationship: 'Self',
    },
    status: 'in-treatment',
    registrationDate: '2024-01-15T09:00:00',
    lastVisitDate: new Date().toISOString(),
    allergies: [
      {
        id: 'alg-001',
        allergen: 'Penicillin',
        reaction: 'Rash, hives',
        severity: 'moderate',
        status: 'active',
      },
    ],
    currentMedications: [
      {
        id: 'med-001',
        patientId: 'pat-001',
        name: 'Metformin',
        dosage: '500mg',
        route: 'Oral',
        frequency: 'Twice daily',
        startDate: '2023-06-01',
        prescribedBy: 'Dr. Sarah Johnson',
        status: 'active',
        indication: 'Type 2 Diabetes',
      },
    ],
    encounters: [
      {
        id: 'enc-001',
        patientId: 'pat-001',
        encounterType: 'emergency',
        status: 'active',
        admitDate: new Date().toISOString(),
        chiefComplaint: 'Chest pain, shortness of breath',
        attendingPhysicianId: 'staff-1',
        attendingPhysicianName: 'Dr. Sarah Johnson',
        roomNumber: 'ER-3',
        diagnosis: [
          {
            id: 'diag-001',
            code: 'I20.9',
            description: 'Angina pectoris, unspecified',
            type: 'primary',
            status: 'suspected',
          },
        ],
      },
    ],
    vitalsHistory: [
      {
        id: 'vit-001',
        patientId: 'pat-001',
        timestamp: new Date().toISOString(),
        recordedBy: 'Nurse Adeyemi',
        temperature: 37.2,
        temperatureUnit: 'C',
        bloodPressureSystolic: 152,
        bloodPressureDiastolic: 98,
        heartRate: 94,
        respiratoryRate: 20,
        oxygenSaturation: 96,
        weight: 82,
        weightUnit: 'kg',
        height: 178,
        heightUnit: 'cm',
        painScore: 7,
      },
    ],
    labResults: [
      {
        id: 'lab-001',
        patientId: 'pat-001',
        orderedBy: 'Dr. Sarah Johnson',
        orderedDate: new Date().toISOString(),
        status: 'resulted',
        category: 'Cardiac',
        testName: 'Troponin I',
        priority: 'stat',
        resultDate: new Date().toISOString(),
        results: [
          { name: 'Troponin I', value: '0.12', unit: 'ng/mL', referenceRange: '< 0.04', flag: 'H' },
          { name: 'BNP', value: '320', unit: 'pg/mL', referenceRange: '< 100', flag: 'H' },
        ],
      },
    ],
    imagingOrders: [
      {
        id: 'img-001',
        patientId: 'pat-001',
        orderedBy: 'Dr. Sarah Johnson',
        orderedDate: new Date().toISOString(),
        modality: 'X-Ray',
        bodyPart: 'Chest',
        clinicalIndication: 'Chest pain, rule out pneumothorax',
        priority: 'stat',
        status: 'completed',
        findings: 'No acute cardiopulmonary process. Heart size normal.',
        impression: 'Unremarkable chest X-ray.',
        radiologist: 'Dr. Michael Okonkwo',
      },
    ],
    clinicalNotes: [
      {
        id: 'note-001',
        patientId: 'pat-001',
        encounterId: 'enc-001',
        authorId: 'staff-1',
        authorName: 'Dr. Sarah Johnson',
        timestamp: new Date().toISOString(),
        type: 'soap',
        title: 'Emergency Department Note',
        subjective: 'Patient is a 46-year-old male presenting with acute chest pain radiating to the left arm, onset 2 hours ago. Associated shortness of breath. History of hypertension and diabetes.',
        objective: 'BP: 152/98, HR: 94, RR: 20, SpO2: 96%, Temp: 37.2°C. Alert and oriented. Diaphoretic. Mild respiratory distress.',
        assessment: 'Acute coronary syndrome, rule out NSTEMI. Hypertensive urgency.',
        plan: 'Aspirin 325mg, Nitroglycerin PRN, ECG, Troponin serial, Chest X-ray, Cardiology consult pending.',
        isSigned: true,
        signedAt: new Date().toISOString(),
      },
    ],
    triageAssessments: [
      {
        id: 'tri-001',
        patientId: 'pat-001',
        encounterId: 'enc-001',
        triageNurseId: 'staff-3',
        triageNurseName: 'Nurse Adeyemi',
        arrivalTime: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
        triageTime: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
        chiefComplaint: 'Chest pain and shortness of breath',
        onset: 'Sudden',
        duration: '2 hours',
        severity: 8,
        esiLevel: 2,
        vitals: {
          temperature: 37.2,
          temperatureUnit: 'C',
          bloodPressureSystolic: 152,
          bloodPressureDiastolic: 98,
          heartRate: 94,
          respiratoryRate: 20,
          oxygenSaturation: 96,
          painScore: 7,
        },
        symptoms: ['Chest pain', 'Shortness of breath', 'Diaphoresis', 'Left arm pain'],
        allergiesConfirmed: true,
        medicationsConfirmed: true,
      },
    ],
  },
  {
    id: 'pat-002',
    mrn: 'MRN20240002',
    firstName: 'Amaka',
    lastName: 'Okafor',
    dateOfBirth: '1995-07-14',
    gender: 'female',
    phone: '555-2001',
    address: {
      street: '7 Victoria Island',
      city: 'Lagos',
      state: 'Lagos',
      zip: '101241',
      country: 'Nigeria',
    },
    bloodType: 'B+',
    maritalStatus: 'Single',
    emergencyContacts: [
      {
        id: 'ec-002',
        name: 'Chidi Okafor',
        relationship: 'Father',
        phone: '555-2002',
      },
    ],
    status: 'waiting',
    registrationDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    lastVisitDate: new Date().toISOString(),
    allergies: [],
    currentMedications: [],
    encounters: [
      {
        id: 'enc-002',
        patientId: 'pat-002',
        encounterType: 'emergency',
        status: 'active',
        admitDate: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        chiefComplaint: 'Severe headache, fever',
        attendingPhysicianId: 'staff-1',
        attendingPhysicianName: 'Dr. Sarah Johnson',
      },
    ],
    vitalsHistory: [],
    labResults: [],
    imagingOrders: [],
    clinicalNotes: [],
    triageAssessments: [
      {
        id: 'tri-002',
        patientId: 'pat-002',
        encounterId: 'enc-002',
        triageNurseId: 'staff-3',
        triageNurseName: 'Nurse Adeyemi',
        arrivalTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        triageTime: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
        chiefComplaint: 'Severe headache, fever',
        onset: 'Gradual',
        duration: '6 hours',
        severity: 7,
        esiLevel: 2,
        vitals: {
          temperature: 39.4,
          temperatureUnit: 'C',
          bloodPressureSystolic: 118,
          bloodPressureDiastolic: 76,
          heartRate: 110,
          respiratoryRate: 22,
          oxygenSaturation: 98,
          painScore: 8,
        },
        symptoms: ['Headache', 'Fever', 'Neck stiffness', 'Photophobia'],
        allergiesConfirmed: true,
        medicationsConfirmed: true,
      },
    ],
  },
  {
    id: 'pat-003',
    mrn: 'MRN20240003',
    firstName: 'Emmanuel',
    lastName: 'Balogun',
    dateOfBirth: '2010-02-28',
    gender: 'male',
    phone: '555-3001',
    address: {
      street: '22 Ikeja',
      city: 'Lagos',
      state: 'Lagos',
      zip: '100001',
      country: 'Nigeria',
    },
    bloodType: 'A+',
    emergencyContacts: [
      {
        id: 'ec-003',
        name: 'Grace Balogun',
        relationship: 'Mother',
        phone: '555-3002',
      },
    ],
    status: 'in-triage',
    registrationDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    lastVisitDate: new Date().toISOString(),
    allergies: [
      {
        id: 'alg-002',
        allergen: 'Sulfa drugs',
        reaction: 'Anaphylaxis',
        severity: 'life-threatening',
        status: 'active',
      },
    ],
    currentMedications: [],
    encounters: [
      {
        id: 'enc-003',
        patientId: 'pat-003',
        encounterType: 'emergency',
        status: 'active',
        admitDate: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
        chiefComplaint: 'Fall from bicycle, arm pain',
        attendingPhysicianId: 'staff-2',
        attendingPhysicianName: 'Dr. Michael Okonkwo',
      },
    ],
    vitalsHistory: [],
    labResults: [],
    imagingOrders: [
      {
        id: 'img-002',
        patientId: 'pat-003',
        orderedBy: 'Dr. Michael Okonkwo',
        orderedDate: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        modality: 'X-Ray',
        bodyPart: 'Left forearm',
        clinicalIndication: 'Fall, rule out fracture',
        priority: 'urgent',
        status: 'in-progress',
      },
    ],
    clinicalNotes: [],
    triageAssessments: [],
  },
];
